### PR TITLE
Expired reason iota fix

### PR DESCRIPTION
**Pull request by jgheewala**

### CODE REVIEW

**Comment by jgheewala** [comment]
rebasing https://github.com/allegro/bigcache/pull/181 to versions/v3-prep

**Comment by janisz** [comment]
What exactly does it fix? Can you provide a failing test that is fixed by this change?

**Comment by jgheewala** [comment]
@janisz this PR is mainly moving https://github.com/allegro/bigcache/pull/181 to "v3-prep" branch. All the discussion can be found in original PR..

I can certainly add test case for this scenario.

**Comment by jgheewala** [comment]
@janisz i already wrote test case back `TestBigCache_GetWithInfo` and that tests this scenario.. 

Let me know if you need more testing on top of that. 

Also https://github.com/allegro/bigcache/pull/216 adjusted the values for const. 

My changes are just adding iota for better code readability and removing the explicit values.

**Review by janisz — APPROVED** [review]

**Comment by jgheewala** [comment]
@mxplusb will this make cut for v3 ?

**Review by cristaloleg — APPROVED** [review]

**Pull request merged**
