### PR TITLE
Go module support

### PR DESCRIPTION
**Pull request by maciej**
This commit adds Go modules[1] support.

I ran:
```sh
go mod init github.com/allegro/bigcache
go mod tidy
```
in the project directory

[1] https://github.com/golang/go/wiki/Modules

### CODE REVIEW

**Comment by cristaloleg** [comment]
Thank you for the contribution.
AFAIR we need to release Bigcache v2 with go.mod so no one one 1.x will get a broken build.
@mxplusb do you've any additional info?

**Comment by maciej** [comment]
I believe go modules are backward compatible, so addition of `go.mod` should not break existing builds not based on modules.

**Comment by cristaloleg** [comment]
There was a thread on chi router regarding go modules, and they complained
about it. Maybe I’m mixing 2 different stories into one.

**Comment by mxplusb** [comment]
@maciej this is shipped in [2.0!](https://github.com/allegro/bigcache/releases/tag/v2.0.0)

**Comment by maciej** [comment]
Great, thank you!

**Pull request closed without merging**
