### PR TITLE
Skip hashing

### PR DESCRIPTION
**Pull request by SlashGordon**
I need a way to provide my own hash value without string to uint64 conversion.
I think the simplest solution is to provide setter and getter with the ability to skip hashing.

### CODE REVIEW

**Review by cristaloleg — CHANGES_REQUESTED** [review]
See linter fails

**Comment by SlashGordon** [comment]
I have fixed the linter errors :)

**Review by cristaloleg — DISMISSED** [review]

**Comment by cristaloleg** [comment]
@janisz @mxplusb if ok - let's merge

**Comment by janisz** [comment]
I'm not sure about it. If you need to get set without key why you propose to function that requires key and hashed key?
Can't you just use custom hasher?

If this is about to land I think we should use `GetByHash` in `Get` just to simplify code and reduce needed tests

**Pull request closed without merging**
