### PR TITLE
Update paths to v2

### PR DESCRIPTION
**Pull request by cristaloleg**

### CODE REVIEW

**Comment by mxplusb** [comment]
TBH we don't need to do path updates. When installing/downloading, if you call `go get github.com/allegro/bigcache@v1.0.0`, you get it at version 1, and `go get github.com/allegro/bigcache@v2.0.0`.

**Comment by mxplusb** [comment]
> if you call go get github.com/allegro/bigcache@v1.0.0

Thinking about it, I'm not sure this would work since there is no `go.mod`.

**Comment by gracenoah** [comment]
I suspect that running `go get github.com/allegro/bigcache@v2.0.0` would add bigcache to your go.mod with the `+incompatible` suffix to work around the requirement for a `/v2` suffix. I'm surprised that no tests failed without the v2 suffix though.
See https://github.com/golang/go/wiki/Modules#can-a-module-consume-a-v2-package-that-has-not-opted-into-modules-what-does-incompatible-mean

**Comment by cristaloleg** [comment]
@janisz please, have a look

**Comment by janisz** [comment]
>I'm surprised that no tests failed without the v2 suffix though.

We need to enable modules on travis https://dave.cheney.net/2018/07/16/using-go-modules-with-travis-ci

**Comment by cristaloleg** [comment]
Huh, wait, why does it work on master? 🤔

**Comment by cristaloleg** [comment]
Or in this PR also, `Go 1.x` is `1.12.3` and modules aren't enabled by default

**Comment by cristaloleg** [comment]
No, wait, why does it work without explicit `Go111MODULES` ? ;D

**Comment by cristaloleg** [comment]
Ah, Travis is smart, we're outside of a GOPATH 
https://travis-ci.org/allegro/bigcache/jobs/550658078#L437

**Pull request merged**
