### PR TITLE
Delete caches_bench_test.go

### LINKED ISSUE #162: Create separate benchmarks repo
Based on this [comment](https://github.com/allegro/bigcache/pull/155#issuecomment-526491724) we can move benchmarks dependencies to another repo. This will reduce number of deps in go.mod, which will improve build/fetch times for the users.

### PR DESCRIPTION
**Pull request by cristaloleg**
Fixes #162

### CODE REVIEW

**Comment by mxplusb** [comment]
It looks okay to me, I would go ahead and run `go mod tidy` since the upstream references are gone, that way it'll clean up the references, too. Might as well do it in one swoop.

**Comment by cristaloleg** [comment]
better late than never

**Comment by cristaloleg** [comment]
@janisz @mxplusb review please :)

**Comment by janisz** [comment]
Can you update https://github.com/allegro/bigcache#writes-and-reads with links to benchmarks

**Comment by janisz** [comment]
@cristaloleg Ping

**Comment by cristaloleg** [comment]
@janisz yep, I know ;D

**Comment by janisz** [comment]
https://github.com/allegro/bigcache/pull/186

**Pull request closed without merging**
