### PR TITLE
fix queue import path

### PR DESCRIPTION
**Pull request by leaxoy**

### CODE REVIEW

**Comment by leaxoy** [comment]
And can you bump version, then I will update my mod

**Comment by cristaloleg** [comment]
@leaxoy sure, v2.1.2 https://github.com/allegro/bigcache/releases/tag/v2.1.2

**Comment by leaxoy** [comment]
Thanks a lot 😀

**Comment by leaxoy** [comment]
Another suggest, split benchmarks with other lib like freecache into a new repo to reduce mod deps.

**Comment by cristaloleg** [comment]
@leaxoy yeah, this is a long running idea. Maybe it's time to make it real. Thanks for a reminder 👍

**Pull request merged**
