### PR TITLE
HTTP Server is done!

### LINKED ISSUE #56: Proposal: Server Package
It would be awesome to see a basic/reference HTTP implementation package here so this can be easily deployed as a basic HTTP cache.

Pros:
* So fast.
* Easily deployable to Cloud Foundry, Heroku, etc.

Here is what I am thinking. An API path like this:

```
GET /api/v1/{key}
PUT /api/v1/{key}
```

For configuration:

```json
{
	"LifeWindow": "10m",
	"MaxEntrySize": "500KB",
	"Verbose": true,
	"HardMaxCacheSize": "8192KB"
}
```

Configuration can be read from either CLI flags, environment variables, or `.bigcacherc`. Some of the cache configurations can be inferred/defaulted.

### PR DESCRIPTION
**Pull request by mxplusb**
This should close #56, since the server now has the entire cache API surface (to my knowledge).

This one had a refactor of some components. I moved the handlers and middleware to their own files, making them easier to extend for better feature support down the road.

I also added `DELETE`, the stats API, and the respective tests.

Closes #56

### CODE REVIEW

**Comment by janisz** [comment]
@mxplusb There are some conflicts

**Comment by mxplusb** [comment]
Alright, fixed the merge conflict - had to rewind and rebase, my bad. Travis is complaining about something in the diff, but I don't know what it is. @janisz can you provide a pointer on what is causing it to fail?

**Comment by janisz** [comment]
@mxplusb It's just formatting, diff shows you what should be fixed

> [Go files must be formatted with gofmt. Following files has problem:
./server/cache_handlers.go
./server/server.go
./server/server_test.go
./server/stats_handler.go](
https://travis-ci.org/allegro/bigcache/jobs/308737574#L504-L507)

**Comment by mxplusb** [comment]
Fixed the formatting issues.

**Comment by janisz** [comment]
@mxplusb Thanks!

**Pull request merged**
