### PR TITLE
fix(init): initialShardSize ignored HardMaxCacheSize, and so the initial size can exceed the limit

### PR DESCRIPTION
**Pull request by leeransetton**
https://github.com/allegro/bigcache/issues/139

### CODE REVIEW

**Comment by cristaloleg** [comment]
Thanks! 🎉

**Comment by leeransetton** [comment]
@cristaloleg when will this code be released as a version?

**Comment by cristaloleg** [comment]
Sure, give me 10 mins :)

**Comment by cristaloleg** [comment]
@leeransetton done :) https://github.com/allegro/bigcache/releases/tag/v2.2.2

**Comment by leeransetton** [comment]
Thanks @cristaloleg

**Pull request merged**
